---
excerpt: "blog about understanding promises"
title: "Js Promises Dymystified"
publishedAt: "2022-04-16"
---

# PROMISES

It's a Javascript Object which link the producing code (request , time taking functions) to consuming code (function which depend on the result of the producing code).

### Producer

```jsx
let promises = new Promise((resolve, reject) => {
  // executor
  setTimeout(() => {
    reject("done");
  }, 100);
});

promises.catch((err) => {
  console.log("error");
});
```

### Consumer

```jsx
.then((result)=>{} , (error)=>{ })
.catch((error)=>{})  //alternative to catch .then(null,(err)=>{ })
.finally()

```

### NOTE :

".finally"

finally is a good handler for performing the cleanup, e.g. stopping our loading indicators, as they are not needed anymore, no matter what the outcome is.

".then"

Returns a promise , so thats why we can chain more .then.then

### Promising Chaining

When we return promises in promise handler like in .then

".catch"

In catch we can also handle the error and make a new promise after that

```jsx
.catch((err)=>{console.log(err)}.then()
```

### APIS

### Promise.all([promise1,promise2, ..npromise])

promise.all takes an array of promises and returns a new promise.

The new promise is resolved when all the promises has been resolved and the result of the promises stored in array return as a result.

In cases of error the promise.all will return reject and other promise will still execute but the results are ignored.

Code Trivia

```jsx
Promise.all([
  new Promise((resolve, reject) => {
    setTimeout(() => resolve(1), 1000);
  }),
  new Promise((resolve, reject) => {
    console.log("2 nd promise executed");
    setTimeout(() => reject(1), 1000);
  }),
  3,
]).then(alert);
```

- solution
  1,2,3 // if there is not a promises in array then it will be resulted as it is

### Promise.allSettled([promise1, ...promises])

Same as Promise.all But it does not ignore the result of reject promises.

```jsx
[
  {status: 'fulfilled', value: ...response...},
  {status: 'fulfilled', value: ...response...},
  {status: 'rejected', reason: ...error object...}
]
```

### Promise.race([])

It waits for the first promises to settle(resolve/result) and store it into the result.

### Promise.any([])

It waits for the first promises to resolve and store it into the result.

### Unhandled Rejection

It is an occurrence when a promise error is not handled at the end of the microtask queue.

Microtask are async handlers~~

Code :

```jsx
let promise = Promise.resolve();

promise.then(() => alert("promise done!"));

alert("code finished");
```

```jsx
let promises = new Promise(()=>throw "error")
setTimeout(()=>{
promises.catch((err)=>{console.log(data})
})
window.addEventListener('unhandledrejection', event => alert(event.reason));
```

### Promise.all from scratch

```jsx
Promise.all = function (promises) {
  let result = [];
  return new Promise((resolve, reject) => {
    promises.forEach((promise, index) => {
      promise
        .then((res) => {
          result.push(res);
          if (result.length === promises.length) {
            resolve(result);
          }
        })
        .catch((err) => {
          reject(err);
        });
    });
  });
};

Promise.all([
  new Promise((resolve) => setTimeout(() => resolve(1), 3000)), // 1
  new Promise((resolve) => resolve("sadd")), // 2
  new Promise((resolve) => setTimeout(() => resolve(3), 1000)), // 3
]).then((res) => {
  console.log(res);
});
```
